import {
  LayoutDashboard,
  Package,
  Tags,
  BadgeCheck,
  Truck,
  Users,
  Warehouse,
  MapPin,
  ShoppingCart,
  PackageCheck,
  ArrowDownToLine,
  ArrowUpFromLine,
  ArrowLeftRight,
  SlidersHorizontal,
  ClipboardCheck,
  FileBarChart,
  UserCog,
  ScrollText,
  Settings,
  UserRound,
} from 'lucide-react';

export const NAV_SECTIONS = [
  {
    section: 'Utama',
    items: [
      { to: '/', label: 'Dashboard', icon: LayoutDashboard, permission: 'dashboard:view' },
      { to: '/reports', label: 'Laporan', icon: FileBarChart, permission: 'reports:view' },
    ],
  },
  {
    section: 'Master Data',
    items: [
      { to: '/products', label: 'Produk', icon: Package, permission: 'products:view' },
      { to: '/categories', label: 'Kategori', icon: Tags, permission: 'categories:view' },
      { to: '/brands', label: 'Brand', icon: BadgeCheck, permission: 'brands:view' },
      { to: '/suppliers', label: 'Supplier', icon: Truck, permission: 'suppliers:view' },
      { to: '/customers', label: 'Pelanggan', icon: Users, permission: 'customers:view' },
      { to: '/warehouses', label: 'Gudang', icon: Warehouse, permission: 'warehouses:view' },
      { to: '/locations', label: 'Lokasi', icon: MapPin, permission: 'locations:view' },
    ],
  },
  {
    section: 'Transaksi',
    items: [
      { to: '/purchase-orders', label: 'Purchase Order', icon: ShoppingCart, permission: 'purchase_orders:view' },
      { to: '/goods-receipts', label: 'Penerimaan Barang', icon: PackageCheck, permission: 'goods_receipts:view' },
      { to: '/stock-in', label: 'Stock In', icon: ArrowDownToLine, permission: 'stock_ins:view' },
      { to: '/stock-out', label: 'Stock Out', icon: ArrowUpFromLine, permission: 'stock_outs:view' },
      { to: '/transfers', label: 'Transfer Stok', icon: ArrowLeftRight, permission: 'transfers:view' },
      { to: '/adjustments', label: 'Penyesuaian Stok', icon: SlidersHorizontal, permission: 'adjustments:view' },
      { to: '/opnames', label: 'Opname Stok', icon: ClipboardCheck, permission: 'opnames:view' },
    ],
  },
  {
    section: 'Sistem',
    items: [
      { to: '/users', label: 'Pengguna', icon: UserCog, permission: 'users:view' },
      { to: '/audit-logs', label: 'Log Aktivitas', icon: ScrollText, permission: 'audit:view' },
      { to: '/settings', label: 'Pengaturan', icon: Settings, permission: 'settings:view' },
    ],
  },
  {
    section: 'Akun',
    items: [{ to: '/profile', label: 'Profil Saya', icon: UserRound, permission: null }],
  },
];

export const PERMISSION_LABELS = {
  'dashboard:view': 'Melihat dashboard',
  'products:view': 'Melihat produk',
  'products:create': 'Membuat produk',
  'products:update': 'Mengubah produk',
  'products:delete': 'Menghapus produk',
  'products:import': 'Import produk',
  'products:export': 'Ekspor produk',
  'categories:view': 'Melihat kategori',
  'categories:manage': 'Mengelola kategori',
  'brands:view': 'Melihat brand',
  'brands:manage': 'Mengelola brand',
  'suppliers:view': 'Melihat supplier',
  'suppliers:manage': 'Mengelola supplier',
  'customers:view': 'Melihat pelanggan',
  'customers:manage': 'Mengelola pelanggan',
  'warehouses:view': 'Melihat gudang',
  'warehouses:manage': 'Mengelola gudang',
  'locations:view': 'Melihat lokasi',
  'locations:manage': 'Mengelola lokasi',
  'purchase_orders:view': 'Melihat purchase order',
  'purchase_orders:manage': 'Mengelola purchase order',
  'purchase_orders:approve': 'Menyetujui purchase order',
  'goods_receipts:view': 'Melihat penerimaan barang',
  'goods_receipts:manage': 'Mengelola penerimaan barang',
  'stock_ins:view': 'Melihat stock in',
  'stock_ins:manage': 'Mengelola stock in',
  'stock_outs:view': 'Melihat stock out',
  'stock_outs:create': 'Membuat stock out',
  'stock_outs:approve': 'Menyetujui stock out',
  'transfers:view': 'Melihat transfer stok',
  'transfers:create': 'Membuat transfer stok',
  'transfers:approve': 'Menyetujui transfer stok',
  'adjustments:view': 'Melihat penyesuaian stok',
  'adjustments:create': 'Membuat penyesuaian stok',
  'adjustments:approve': 'Menyetujui penyesuaian stok',
  'opnames:view': 'Melihat opname',
  'opnames:create': 'Membuat opname',
  'opnames:approve': 'Menyetujui opname',
  'movements:view': 'Melihat riwayat stok',
  'movements:export': 'Ekspor riwayat stok',
  'reports:view': 'Melihat laporan',
  'reports:export': 'Ekspor laporan',
  'notifications:view': 'Melihat notifikasi',
  'users:view': 'Melihat pengguna',
  'users:manage': 'Mengelola pengguna',
  'audit:view': 'Melihat log aktivitas',
  'settings:view': 'Melihat pengaturan',
  'settings:manage': 'Mengelola pengaturan',
  'backup:manage': 'Mengelola backup',
};
