import {
  LayoutDashboard,
  Package,
  Tags,
  BadgeCheck,
  Truck,
  Users,
  Warehouse,
  MapPin,
  ShoppingCart,
  PackageCheck,
  ArrowDownToLine,
  ArrowUpFromLine,
  ArrowLeftRight,
  SlidersHorizontal,
  ClipboardCheck,
  FileBarChart,
  UserCog,
  ScrollText,
  Settings,
  UserRound,
} from 'lucide-react';

export const NAV_SECTIONS = [
  {
    section: 'Main',
    items: [
      { to: '/', label: 'Dashboard', icon: LayoutDashboard, permission: 'dashboard:view' },
      { to: '/reports', label: 'Reports', icon: FileBarChart, permission: 'reports:view' },
    ],
  },
  {
    section: 'Master Data',
    items: [
      { to: '/products', label: 'Products', icon: Package, permission: 'products:view' },
      { to: '/categories', label: 'Categories', icon: Tags, permission: 'categories:view' },
      { to: '/brands', label: 'Brand', icon: BadgeCheck, permission: 'brands:view' },
      { to: '/suppliers', label: 'Supplier', icon: Truck, permission: 'suppliers:view' },
      { to: '/customers', label: 'Customers', icon: Users, permission: 'customers:view' },
      { to: '/warehouses', label: 'Warehouses', icon: Warehouse, permission: 'warehouses:view' },
      { to: '/locations', label: 'Locations', icon: MapPin, permission: 'locations:view' },
    ],
  },
  {
    section: 'Transactions',
    items: [
      { to: '/purchase-orders', label: 'Purchase Order', icon: ShoppingCart, permission: 'purchase_orders:view' },
      { to: '/goods-receipts', label: 'Goods Receipts', icon: PackageCheck, permission: 'goods_receipts:view' },
      { to: '/stock-in', label: 'Stock In', icon: ArrowDownToLine, permission: 'stock_ins:view' },
      { to: '/stock-out', label: 'Stock Out', icon: ArrowUpFromLine, permission: 'stock_outs:view' },
      { to: '/transfers', label: 'Stock Transfer', icon: ArrowLeftRight, permission: 'transfers:view' },
      { to: '/adjustments', label: 'Stock Adjustment', icon: SlidersHorizontal, permission: 'adjustments:view' },
      { to: '/opnames', label: 'Stock Opname', icon: ClipboardCheck, permission: 'opnames:view' },
    ],
  },
  {
    section: 'System',
    items: [
      { to: '/users', label: 'Users', icon: UserCog, permission: 'users:view' },
      { to: '/audit-logs', label: 'Activity Logs', icon: ScrollText, permission: 'audit:view' },
      { to: '/settings', label: 'Settings', icon: Settings, permission: 'settings:view' },
    ],
  },
  {
    section: 'Account',
    items: [{ to: '/profile', label: 'My Profile', icon: UserRound, permission: null }],
  },
];

export const PERMISSION_LABELS = {
  'dashboard:view': 'View dashboard',
  'products:view': 'View products',
  'products:create': 'Create products',
  'products:update': 'Update products',
  'products:delete': 'Delete products',
  'products:import': 'Import products',
  'products:export': 'Export products',
  'categories:view': 'View categories',
  'categories:manage': 'Manage categories',
  'brands:view': 'View brands',
  'brands:manage': 'Manage brands',
  'suppliers:view': 'View suppliers',
  'suppliers:manage': 'Manage suppliers',
  'customers:view': 'View customers',
  'customers:manage': 'Manage customers',
  'warehouses:view': 'View warehouses',
  'warehouses:manage': 'Manage warehouses',
  'locations:view': 'View locations',
  'locations:manage': 'Manage locations',
  'purchase_orders:view': 'View purchase orders',
  'purchase_orders:manage': 'Manage purchase orders',
  'purchase_orders:approve': 'Approve purchase orders',
  'goods_receipts:view': 'View goods receipts',
  'goods_receipts:manage': 'Manage goods receipts',
  'stock_ins:view': 'View stock ins',
  'stock_ins:manage': 'Manage stock ins',
  'stock_outs:view': 'View stock outs',
  'stock_outs:create': 'Create stock outs',
  'stock_outs:approve': 'Approve stock outs',
  'transfers:view': 'View stock transfers',
  'transfers:create': 'Create stock transfers',
  'transfers:approve': 'Approve stock transfers',
  'adjustments:view': 'View stock adjustments',
  'adjustments:create': 'Create stock adjustments',
  'adjustments:approve': 'Approve stock adjustments',
  'opnames:view': 'View stock opnames',
  'opnames:create': 'Create stock opnames',
  'opnames:approve': 'Approve stock opnames',
  'movements:view': 'View stock movements',
  'movements:export': 'Export stock movements',
  'reports:view': 'View reports',
  'reports:export': 'Export reports',
  'notifications:view': 'View notifications',
  'users:view': 'View users',
  'users:manage': 'Manage users',
  'audit:view': 'View activity logs',
  'settings:view': 'View settings',
  'settings:manage': 'Manage settings',
  'backup:manage': 'Manage backups',
};
